name: pls
description: pls is a lightweight library for parsing pls documents from document string.
version: 1.0.4
homepage: https://github.com/Andromo-App-Maker/pls

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  equatable: 2.0.5

dev_dependencies:
  lint: 2.2.0
  test: ^1.17.10
