name: pls
description: pls is a lightweight library for parsing pls documents from document string.
version: 1.0.2
homepage: https://github.com/Andromo-App-Maker/pls

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  test: ^1.17.10
  lints: ^1.0.1
